name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test with latest version
        uses: ./
      - run: |
          TAG_NAME=$(curl -s https://api.github.com/repos/idc101/git-mkver/releases/latest | jq -r '.tag_name')
          VERSION="${TAG_NAME//v/}"
          
          [[ $(git mkver | grep -o "$VERSION") == "$VERSION" ]] || exit 1
          
      - name: Test with specific version
        uses: ./
        with:
          version: "1.1.1"
      - run: |
          [[ $(git mkver | grep -o "1.1.1") == "1.1.1" ]] || exit 1
